-- Migration 076: Rule-Based Intelligence Layer
-- Creates smart_alerts and event_health_scores tables for the always-on
-- intelligence engine (no AI API required — pure rule-based logic).
--
-- smart_alerts      — alerts generated by rule groups (guest, finance, vendor, runsheet, f&b, team)
-- event_health_scores — computed 0-100 score per event with per-dimension breakdown

-- ─── Severity enum ──────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'alert_severity') THEN
    CREATE TYPE alert_severity AS ENUM ('info', 'warning', 'critical');
  END IF;
END$$;

-- ─── smart_alerts ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS smart_alerts (
  id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  event_id         UUID          REFERENCES events(id) ON DELETE CASCADE,

  -- Rule identity — used for deduplication (same rule firing twice on same event = upsert)
  alert_type       VARCHAR(100)  NOT NULL,

  severity         alert_severity NOT NULL DEFAULT 'info',
  title            VARCHAR(255)  NOT NULL,
  message          TEXT          NOT NULL,

  -- Arbitrary structured context (e.g. { "vendor_id": "...", "confirmed": 2, "total": 5 })
  metadata         JSONB         NOT NULL DEFAULT '{}',

  -- Dismissal
  is_dismissed     BOOLEAN       NOT NULL DEFAULT false,
  dismissed_by     UUID          REFERENCES profiles(id) ON DELETE SET NULL,
  dismissed_at     TIMESTAMPTZ,

  -- Auto-expiry — alerts are purged after this timestamp if not dismissed
  expires_at       TIMESTAMPTZ,

  created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),

  -- Deduplication: one active alert per (event, alert_type) pair
  CONSTRAINT uq_smart_alert_event_type UNIQUE (event_id, alert_type)
);

-- For fetching event-level active alerts quickly
CREATE INDEX IF NOT EXISTS idx_smart_alerts_event_active
  ON smart_alerts (event_id, is_dismissed)
  WHERE is_dismissed = false;

-- For dashboard-level alert panel (tenant-wide, severity-filtered)
CREATE INDEX IF NOT EXISTS idx_smart_alerts_tenant_severity
  ON smart_alerts (tenant_id, severity, is_dismissed)
  WHERE is_dismissed = false;

-- For expiry cleanup job
CREATE INDEX IF NOT EXISTS idx_smart_alerts_expires_at
  ON smart_alerts (expires_at)
  WHERE expires_at IS NOT NULL AND is_dismissed = false;

-- ─── event_health_scores ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS event_health_scores (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id             UUID        NOT NULL UNIQUE REFERENCES events(id) ON DELETE CASCADE,

  -- Overall 0-100 score
  overall_score        INTEGER     NOT NULL DEFAULT 100 CHECK (overall_score BETWEEN 0 AND 100),

  -- Per-dimension scores: { guests, finance, vendors, runsheet, fnb, team }
  dimension_scores     JSONB       NOT NULL DEFAULT '{"guests":100,"finance":100,"vendors":100,"runsheet":100,"fnb":100,"team":100}',

  computed_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  next_compute_at      TIMESTAMPTZ,

  -- Snapshot of active alert counts at computation time
  alert_count_critical INTEGER     NOT NULL DEFAULT 0,
  alert_count_warning  INTEGER     NOT NULL DEFAULT 0,
  alert_count_info     INTEGER     NOT NULL DEFAULT 0
);

-- For cron: find events whose health score is stale (next_compute_at has passed)
CREATE INDEX IF NOT EXISTS idx_health_scores_stale
  ON event_health_scores (next_compute_at)
  WHERE next_compute_at IS NOT NULL;

-- ─── Trigger: keep updated_at current on smart_alerts ────────────────────────
CREATE OR REPLACE FUNCTION update_smart_alerts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_smart_alerts_updated_at ON smart_alerts;
CREATE TRIGGER trg_smart_alerts_updated_at
  BEFORE UPDATE ON smart_alerts
  FOR EACH ROW EXECUTE FUNCTION update_smart_alerts_updated_at();

-- ─── Comments ─────────────────────────────────────────────────────────────────
COMMENT ON TABLE smart_alerts IS
  'Rule-generated event/tenant alerts from the intelligence engine. Deduplicated by (event_id, alert_type).';

COMMENT ON TABLE event_health_scores IS
  '0-100 health score per event computed from active smart_alerts. Recomputed every 6 hours by cron.';

COMMENT ON COLUMN smart_alerts.alert_type IS
  'Machine-readable rule identifier, e.g. "rsvp_response_rate_low", "vendor_unconfirmed". Used for deduplication.';

COMMENT ON COLUMN smart_alerts.expires_at IS
  'Auto-expiry timestamp. Alerts older than this are considered stale and should be purged by a maintenance job.';

COMMENT ON COLUMN event_health_scores.dimension_scores IS
  'Per-dimension sub-scores as JSON: { guests, finance, vendors, runsheet, fnb, team } each 0-100.';
